---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  check_mode: false
  when: ansible_facts.packages is not defined
  tags: install_postgresql_repo

- block: # Debian/Ubuntu
    - name: Make sure the python3-debian package is present
      ansible.builtin.apt:
        name: python3-debian
        state: present
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      when: "'python3-debian' not in ansible_facts.packages"

    - name: Ensure /etc/apt/sources.list.d directory exists
      ansible.builtin.file:
        path: /etc/apt/sources.list.d
        state: directory
        mode: "0755"
      when: apt_repository | length > 0

    - name: Add repository
      ansible.builtin.deb822_repository:
        name: "{{ item.name | default(item.repo.split('//')[1].split('/')[0] | replace('.', '-')) }}"
        types: "{{ item.types | default(['deb']) }}"
        uris: "{{ item.uris | default(item.repo.split(' ')[1]) }}"
        signed_by: "{{ item.signed_by | default(item.key | default(omit)) }}"
        suites: "{{ item.suites | default(item.repo.split(' ')[2]) }}"
        components: "{{ item.components | default(item.repo.split(' ')[3]) }}"
        enabled: "{{ item.enabled | default(true) }}"
        state: present
      loop: "{{ apt_repository }}"
      when: apt_repository | length > 0

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
  environment: "{{ proxy_env | default({}) }}"
  when: installation_method == "packages" and ansible_os_family == "Debian"
  tags: add_repo
  ignore_errors: "{{ ansible_check_mode }}"
